window.SaiProductCatalog = [
  {
    "sku": "ODISHA-SPR-001",
    "name": "63 mm 3.2 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 710.0,
    "sellingPrice": 710.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-002",
    "name": "63 mm HDPE Pump connection nipple (PCN)",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 340.0,
    "sellingPrice": 340.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-003",
    "name": "63 mm HDPE Tee connector",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 380.0,
    "sellingPrice": 380.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-004",
    "name": "63 mm HDPE Bend",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 220.0,
    "sellingPrice": 220.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-005",
    "name": "63 mm Foot batten with sprinkler adopter",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 410.0,
    "sellingPrice": 410.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-006",
    "name": "63 mm End caps",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 80.0,
    "sellingPrice": 80.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-007",
    "name": "75 mm 2.5 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 825.0,
    "sellingPrice": 825.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-008",
    "name": "75 mm HDPE Pump connection nipple (PCN)",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 400.0,
    "sellingPrice": 400.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-009",
    "name": "75 mm HDPE Tee connector",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 430.0,
    "sellingPrice": 430.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-010",
    "name": "75 mm HDPE Bend",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 315.0,
    "sellingPrice": 315.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-011",
    "name": "75 mm Foot batten with sprinkler adopter",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 475.0,
    "sellingPrice": 475.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-012",
    "name": "75 mm End caps",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 125.0,
    "sellingPrice": 125.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-013",
    "name": "90 mm 2.5 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 1200.0,
    "sellingPrice": 1200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-014",
    "name": "90 mm HDPE Pump connection nipple (PCN)",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 600.0,
    "sellingPrice": 600.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-015",
    "name": "90 mm HDPE Tee connector",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 560.0,
    "sellingPrice": 560.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-016",
    "name": "90 mm HDPE Bend",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 395.0,
    "sellingPrice": 395.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-017",
    "name": "90 mm Foot batten with sprinkler adopter",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 570.0,
    "sellingPrice": 570.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-018",
    "name": "90 mm End caps",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 150.0,
    "sellingPrice": 150.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-019",
    "name": "3/4\" Full circle brass sprinkler (covering about 10 m radius at 2.5 Kg/cm2) (Metal)",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 540.0,
    "sellingPrice": 540.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-020",
    "name": "3/4\" Full circle Plastic sprinkler (covering about 10 m radius at 2.5 Kg/cm2) (Plastic)",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 220.0,
    "sellingPrice": 220.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-021",
    "name": "3/4\" Riser pipe 75 cm long with Socket for sprinkler",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 170.0,
    "sellingPrice": 170.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-022",
    "name": "63 mm 4 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 870.0,
    "sellingPrice": 870.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-023",
    "name": "75 mm 3.2 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 1050.0,
    "sellingPrice": 1050.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-024",
    "name": "75 mm 4 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 1160.0,
    "sellingPrice": 1160.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-025",
    "name": "90 mm 3.2 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 1420.0,
    "sellingPrice": 1420.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-SPR-026",
    "name": "90 mm 4 Kg/cm2 Quick action coupled HDPE sprinkler pipe 6 m long with male and female couplers and \"C\" type clamp",
    "category": "Sprinkler Irrigation Components",
    "unit": "No",
    "costPrice": 1760.0,
    "sellingPrice": 1760.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Sprinkler Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-001",
    "name": "12 mm",
    "category": "A PLAIN LATERALS CLASS 2",
    "unit": "Mtr",
    "costPrice": 8.5,
    "sellingPrice": 8.5,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-002",
    "name": "16 mm",
    "category": "A PLAIN LATERALS CLASS 2",
    "unit": "Mtr",
    "costPrice": 13.0,
    "sellingPrice": 13.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-003",
    "name": "20 mm",
    "category": "A PLAIN LATERALS CLASS 2",
    "unit": "Mtr",
    "costPrice": 18.5,
    "sellingPrice": 18.5,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-004",
    "name": "25 mm",
    "category": "A PLAIN LATERALS CLASS 2",
    "unit": "Mtr",
    "costPrice": 34.0,
    "sellingPrice": 34.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-005",
    "name": "32 mm",
    "category": "A PLAIN LATERALS CLASS 2",
    "unit": "Mtr",
    "costPrice": 48.0,
    "sellingPrice": 48.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-006",
    "name": "12 mm - 30 cm",
    "category": "B.1 12 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 10.2,
    "sellingPrice": 10.2,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-007",
    "name": "12 mm - 40 cm",
    "category": "B.1 12 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 10.0,
    "sellingPrice": 10.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-008",
    "name": "12 mm - 50 cm",
    "category": "B.1 12 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 9.4,
    "sellingPrice": 9.4,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-009",
    "name": "12 mm - 60 cm",
    "category": "B.1 12 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 9.0,
    "sellingPrice": 9.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-010",
    "name": "16 mm - 30 cm",
    "category": "B.2 16 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 13.2,
    "sellingPrice": 13.2,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-011",
    "name": "16 mm - 40 cm",
    "category": "B.2 16 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 13.0,
    "sellingPrice": 13.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-012",
    "name": "16 mm - 50 cm",
    "category": "B.2 16 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 12.8,
    "sellingPrice": 12.8,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-013",
    "name": "16 mm - 60 cm",
    "category": "B.2 16 mm CL 2 with NPC Emitters in 2 / 4 LPH.",
    "unit": "Mtr",
    "costPrice": 12.5,
    "sellingPrice": 12.5,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-014",
    "name": "2 / 4 / 8/ 14 LPH",
    "category": "C NPC - ON LINE DRIPPERS- IS - 13487",
    "unit": "No",
    "costPrice": 3.5,
    "sellingPrice": 3.5,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-015",
    "name": "PC - ON LINE DRIPPERS 4/8 LPH",
    "category": "C NPC - ON LINE DRIPPERS- IS - 13487",
    "unit": "No",
    "costPrice": 5.0,
    "sellingPrice": 5.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-016",
    "name": "6 mm Extension Tube",
    "category": "D EXTENSION / MICRO TUBEINGS",
    "unit": "Mtr",
    "costPrice": 3.2,
    "sellingPrice": 3.2,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-017",
    "name": "Micro Tube OD 3.0mm - ID 2 / 2.5 mm",
    "category": "D EXTENSION / MICRO TUBEINGS",
    "unit": "Mtr",
    "costPrice": 2.0,
    "sellingPrice": 2.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-018",
    "name": "Micro Tube OD 3.5 mm- ID 1 / 1.2 / 1.5 mm",
    "category": "D EXTENSION / MICRO TUBEINGS",
    "unit": "Mtr",
    "costPrice": 2.5,
    "sellingPrice": 2.5,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-019",
    "name": "32 mm / 1 \"",
    "category": "E PVC BALL VALVES / CONTROL VALVES",
    "unit": "No",
    "costPrice": 100.0,
    "sellingPrice": 100.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-020",
    "name": "40 mm / 1.25 \"",
    "category": "E PVC BALL VALVES / CONTROL VALVES",
    "unit": "No",
    "costPrice": 120.0,
    "sellingPrice": 120.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-021",
    "name": "50 mm / 1.50 \"",
    "category": "E PVC BALL VALVES / CONTROL VALVES",
    "unit": "No",
    "costPrice": 150.0,
    "sellingPrice": 150.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-022",
    "name": "63 mm / 2.00 \"",
    "category": "E PVC BALL VALVES / CONTROL VALVES",
    "unit": "No",
    "costPrice": 200.0,
    "sellingPrice": 200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-023",
    "name": "75 mm / 2.50 \"",
    "category": "E PVC BALL VALVES / CONTROL VALVES",
    "unit": "No",
    "costPrice": 320.0,
    "sellingPrice": 320.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-024",
    "name": "90 mm / 3.00 \"",
    "category": "E PVC BALL VALVES / CONTROL VALVES",
    "unit": "No",
    "costPrice": 450.0,
    "sellingPrice": 450.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-025",
    "name": "110 mm / 4.00 \"",
    "category": "E PVC BALL VALVES / CONTROL VALVES",
    "unit": "No",
    "costPrice": 750.0,
    "sellingPrice": 750.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-026",
    "name": "50 mm/1.5 \"",
    "category": "F SINGLE UNION BALL VALVES",
    "unit": "No",
    "costPrice": 450.0,
    "sellingPrice": 450.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-027",
    "name": "63 mm/2.0\"",
    "category": "F SINGLE UNION BALL VALVES",
    "unit": "No",
    "costPrice": 520.0,
    "sellingPrice": 520.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-028",
    "name": "75 mm/2.5\"",
    "category": "F SINGLE UNION BALL VALVES",
    "unit": "No",
    "costPrice": 720.0,
    "sellingPrice": 720.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-029",
    "name": "90 mm/3.0\"",
    "category": "F SINGLE UNION BALL VALVES",
    "unit": "No",
    "costPrice": 1290.0,
    "sellingPrice": 1290.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-030",
    "name": "63 mm/2.0\"",
    "category": "G DOUBLE UNION BALL VALVES",
    "unit": "No",
    "costPrice": 580.0,
    "sellingPrice": 580.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-031",
    "name": "75 mm/2.5\"",
    "category": "G DOUBLE UNION BALL VALVES",
    "unit": "No",
    "costPrice": 820.0,
    "sellingPrice": 820.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-032",
    "name": "90 mm/3.0\"",
    "category": "G DOUBLE UNION BALL VALVES",
    "unit": "No",
    "costPrice": 1700.0,
    "sellingPrice": 1700.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-033",
    "name": "Flush Valve 40 mm/ 50 mm",
    "category": "H FLUSH VALVES. PVC",
    "unit": "No",
    "costPrice": 100.0,
    "sellingPrice": 100.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-034",
    "name": "Flush Valve 63 mm/ 75 mm",
    "category": "H FLUSH VALVES. PVC",
    "unit": "No",
    "costPrice": 150.0,
    "sellingPrice": 150.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-035",
    "name": "1\" Air Release valve only",
    "category": "I AIR RELEASE VALVE / VACCUM BREAKER",
    "unit": "No",
    "costPrice": 200.0,
    "sellingPrice": 200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-036",
    "name": "1.5\" Air Release valve only",
    "category": "I AIR RELEASE VALVE / VACCUM BREAKER",
    "unit": "No",
    "costPrice": 250.0,
    "sellingPrice": 250.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-037",
    "name": "0.5\" Vaccum Breaker only",
    "category": "I AIR RELEASE VALVE / VACCUM BREAKER",
    "unit": "No",
    "costPrice": 90.0,
    "sellingPrice": 90.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-038",
    "name": "0.75\" Vaccum Breaker only",
    "category": "I AIR RELEASE VALVE / VACCUM BREAKER",
    "unit": "No",
    "costPrice": 100.0,
    "sellingPrice": 100.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-039",
    "name": "Micro Sprinkler Set",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 25.0,
    "sellingPrice": 25.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-040",
    "name": "Micro Sprinkler - 50 LPH",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 17.0,
    "sellingPrice": 17.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-041",
    "name": "Fogger / Mist Sprayer - 20 LPH",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 17.0,
    "sellingPrice": 17.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-042",
    "name": "SUJAY Aquatuff sprinkler",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 22.0,
    "sellingPrice": 22.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-043",
    "name": "Butterfly Sprinkler - Yellow",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 20.0,
    "sellingPrice": 20.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-044",
    "name": "Adopter for sprinkler",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 5.0,
    "sellingPrice": 5.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-045",
    "name": "Thai Jet - 40 LPH",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 10.0,
    "sellingPrice": 10.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-046",
    "name": "PVC Stake for Micro Sprinkler / Mister - 3 ft.",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 19.0,
    "sellingPrice": 19.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-047",
    "name": "PVC Stake for Micro Sprinkler / Mister - 1 ft.",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 11.0,
    "sellingPrice": 11.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-048",
    "name": "Moulded Stake for Micro Sprinkler - 1 ft",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 12.0,
    "sellingPrice": 12.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-049",
    "name": "4 Way Fogger",
    "category": "J MICRO SPRINKLERS / MISTERS",
    "unit": "No",
    "costPrice": 170.0,
    "sellingPrice": 170.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-050",
    "name": "Mini Sprinkler Head / Nozzle",
    "category": "K MINI SPRINKLERS ITEMS",
    "unit": "No",
    "costPrice": 115.0,
    "sellingPrice": 115.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-051",
    "name": "M S Riser Rod & Assembly",
    "category": "K MINI SPRINKLERS ITEMS",
    "unit": "No",
    "costPrice": 90.0,
    "sellingPrice": 90.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-052",
    "name": "Regular pressure guage",
    "category": "L PRESSURE GUAGE",
    "unit": "No",
    "costPrice": 250.0,
    "sellingPrice": 250.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-053",
    "name": "Glycerine filled pressure guage",
    "category": "L PRESSURE GUAGE",
    "unit": "No",
    "costPrice": 350.0,
    "sellingPrice": 350.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-054",
    "name": "10 cum. - 2\"",
    "category": "M SCREEN FILTER - IS - 12785 ( METAL )",
    "unit": "No",
    "costPrice": 3200.0,
    "sellingPrice": 3200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-055",
    "name": "20 cum. - 2\"",
    "category": "M SCREEN FILTER - IS - 12785 ( METAL )",
    "unit": "No",
    "costPrice": 3700.0,
    "sellingPrice": 3700.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-056",
    "name": "30 cum. - 2.5\"",
    "category": "M SCREEN FILTER - IS - 12785 ( METAL )",
    "unit": "No",
    "costPrice": 4200.0,
    "sellingPrice": 4200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-057",
    "name": "40 cum. - 3\"",
    "category": "M SCREEN FILTER - IS - 12785 ( METAL )",
    "unit": "No",
    "costPrice": 4800.0,
    "sellingPrice": 4800.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-058",
    "name": "50 cum. - 3\"",
    "category": "M SCREEN FILTER - IS - 12785 ( METAL )",
    "unit": "No",
    "costPrice": 5300.0,
    "sellingPrice": 5300.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-059",
    "name": "25 m3/hr x 2 \" - T Type",
    "category": "N SCREEN FILTER - IS - 12785 ( PLASTIC )",
    "unit": "No",
    "costPrice": 2800.0,
    "sellingPrice": 2800.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-060",
    "name": "30 m3/hr x 2.5 \" - T Type",
    "category": "N SCREEN FILTER - IS - 12785 ( PLASTIC )",
    "unit": "No",
    "costPrice": 3200.0,
    "sellingPrice": 3200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-061",
    "name": "40 m3/hr x 3 \" - T Type",
    "category": "N SCREEN FILTER - IS - 12785 ( PLASTIC )",
    "unit": "No",
    "costPrice": 3400.0,
    "sellingPrice": 3400.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-062",
    "name": "50 m3/hr x 3 \" - T Type",
    "category": "N SCREEN FILTER - IS - 12785 ( PLASTIC )",
    "unit": "No",
    "costPrice": 4500.0,
    "sellingPrice": 4500.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-063",
    "name": "25 m3/hr x 2 \" - T Type",
    "category": "O DISC FILTER IS 12785",
    "unit": "No",
    "costPrice": 4500.0,
    "sellingPrice": 4500.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-064",
    "name": "30 m3/hr x 2.5\" - T Type",
    "category": "O DISC FILTER IS 12785",
    "unit": "No",
    "costPrice": 5100.0,
    "sellingPrice": 5100.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-065",
    "name": "40 m3/hr x 3.0\" - T Type",
    "category": "O DISC FILTER IS 12785",
    "unit": "No",
    "costPrice": 5900.0,
    "sellingPrice": 5900.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-066",
    "name": "50 m3/hr x 3.0 \" - T Type",
    "category": "O DISC FILTER IS 12785",
    "unit": "No",
    "costPrice": 6500.0,
    "sellingPrice": 6500.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-067",
    "name": "10 m3/hr x 2 \"",
    "category": "Sand Filter - IS 14606 with PP Back Wash Assembly",
    "unit": "No",
    "costPrice": 22000.0,
    "sellingPrice": 22000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-068",
    "name": "20 m3/hr x 2 \"",
    "category": "Sand Filter - IS 14606 with PP Back Wash Assembly",
    "unit": "No",
    "costPrice": 23000.0,
    "sellingPrice": 23000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-069",
    "name": "25 m3/hr x 2 \"",
    "category": "Sand Filter - IS 14606 with PP Back Wash Assembly",
    "unit": "No",
    "costPrice": 24000.0,
    "sellingPrice": 24000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-070",
    "name": "30 m3/hr x 2.5 \"",
    "category": "Sand Filter - IS 14606 with PP Back Wash Assembly",
    "unit": "No",
    "costPrice": 28000.0,
    "sellingPrice": 28000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-071",
    "name": "40 m3/hr x 3 \"",
    "category": "Sand Filter - IS 14606 with PP Back Wash Assembly",
    "unit": "No",
    "costPrice": 30000.0,
    "sellingPrice": 30000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-072",
    "name": "50 m3/hr x 3 \"",
    "category": "Sand Filter - IS 14606 with PP Back Wash Assembly",
    "unit": "No",
    "costPrice": 34000.0,
    "sellingPrice": 34000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-073",
    "name": "20 m3/hr x 2 \"",
    "category": "Q HYDRO CYCLONE FILTER - IS 14743 METAL",
    "unit": "No",
    "costPrice": 8000.0,
    "sellingPrice": 8000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-074",
    "name": "30 m3/hr x 2.5 \"",
    "category": "Q HYDRO CYCLONE FILTER - IS 14743 METAL",
    "unit": "No",
    "costPrice": 9000.0,
    "sellingPrice": 9000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-075",
    "name": "50 m3/hr x 3\"",
    "category": "Q HYDRO CYCLONE FILTER - IS 14743 METAL",
    "unit": "No",
    "costPrice": 9700.0,
    "sellingPrice": 9700.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-076",
    "name": "25 m3/hr x 2.0 \"",
    "category": "R HYDRO CYCLONE FILTER - IS 14743 PLASTIC",
    "unit": "No",
    "costPrice": 5600.0,
    "sellingPrice": 5600.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-077",
    "name": "30 m3/hr x 2.5 \"",
    "category": "R HYDRO CYCLONE FILTER - IS 14743 PLASTIC",
    "unit": "No",
    "costPrice": 6200.0,
    "sellingPrice": 6200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-078",
    "name": "50 m3/hr x 3.0 \"",
    "category": "R HYDRO CYCLONE FILTER - IS 14743 PLASTIC",
    "unit": "No",
    "costPrice": 7000.0,
    "sellingPrice": 7000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-079",
    "name": "3/4\" / 1\" / 1.5\" / 2 'Ventury with suction port & Assembly",
    "category": "S VENTURY / INJECTORS - IS 14483",
    "unit": "No",
    "costPrice": 2200.0,
    "sellingPrice": 2200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-080",
    "name": "2.5\" 'Ventury with suction port & Assembly",
    "category": "S VENTURY / INJECTORS - IS 14483",
    "unit": "No",
    "costPrice": 2400.0,
    "sellingPrice": 2400.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-081",
    "name": "Fertilizer tank 30 Litres with assembly",
    "category": "T FERTILIZER EQUIPMENT & Drip Line Winder",
    "unit": "No",
    "costPrice": 5500.0,
    "sellingPrice": 5500.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-082",
    "name": "Fertilizer tank 60 Litres with assembly",
    "category": "T FERTILIZER EQUIPMENT & Drip Line Winder",
    "unit": "No",
    "costPrice": 6900.0,
    "sellingPrice": 6900.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-083",
    "name": "Fertilizer Tank 90 Litres with assembly",
    "category": "T FERTILIZER EQUIPMENT & Drip Line Winder",
    "unit": "No",
    "costPrice": 8800.0,
    "sellingPrice": 8800.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-084",
    "name": "Fertilizer Tank 120 Litres with assembly",
    "category": "T FERTILIZER EQUIPMENT & Drip Line Winder",
    "unit": "No",
    "costPrice": 11400.0,
    "sellingPrice": 11400.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-085",
    "name": "Drip Line Winder",
    "category": "T FERTILIZER EQUIPMENT & Drip Line Winder",
    "unit": "No",
    "costPrice": 3500.0,
    "sellingPrice": 3500.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-086",
    "name": "1.5'' NRV",
    "category": "U NON RETURN VALVE",
    "unit": "No",
    "costPrice": 600.0,
    "sellingPrice": 600.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-087",
    "name": "2'' NRV",
    "category": "U NON RETURN VALVE",
    "unit": "No",
    "costPrice": 700.0,
    "sellingPrice": 700.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-088",
    "name": "2.5'' NRV",
    "category": "U NON RETURN VALVE",
    "unit": "No",
    "costPrice": 1200.0,
    "sellingPrice": 1200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-089",
    "name": "1.5'' X 1.5''",
    "category": "V BY PASS ASSEMBLY",
    "unit": "No",
    "costPrice": 1000.0,
    "sellingPrice": 1000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-090",
    "name": "2'' X 1.5''",
    "category": "V BY PASS ASSEMBLY",
    "unit": "No",
    "costPrice": 1200.0,
    "sellingPrice": 1200.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-091",
    "name": "2.5'' X 2''",
    "category": "V BY PASS ASSEMBLY",
    "unit": "No",
    "costPrice": 1400.0,
    "sellingPrice": 1400.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-092",
    "name": "1.5''",
    "category": "W THROTTLE VALVE",
    "unit": "No",
    "costPrice": 1000.0,
    "sellingPrice": 1000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-093",
    "name": "2''",
    "category": "W THROTTLE VALVE",
    "unit": "No",
    "costPrice": 1000.0,
    "sellingPrice": 1000.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-094",
    "name": "2.5''",
    "category": "W THROTTLE VALVE",
    "unit": "No",
    "costPrice": 1700.0,
    "sellingPrice": 1700.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-095",
    "name": "3''",
    "category": "W THROTTLE VALVE",
    "unit": "No",
    "costPrice": 1900.0,
    "sellingPrice": 1900.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-096",
    "name": "110 MM x 4 KG/CM2",
    "category": "X PVC MAIN LINE & SUBMAIN LINE (Rigid PVC Pipe as per IS-4985-1999 with ISI Markings)",
    "unit": "Mtr",
    "costPrice": 218.0,
    "sellingPrice": 218.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-097",
    "name": "90 MM x 4 KG/CM2",
    "category": "X PVC MAIN LINE & SUBMAIN LINE (Rigid PVC Pipe as per IS-4985-1999 with ISI Markings)",
    "unit": "Mtr",
    "costPrice": 168.0,
    "sellingPrice": 168.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-098",
    "name": "75 MM x 4 KG/CM2",
    "category": "X PVC MAIN LINE & SUBMAIN LINE (Rigid PVC Pipe as per IS-4985-1999 with ISI Markings)",
    "unit": "Mtr",
    "costPrice": 120.0,
    "sellingPrice": 120.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-099",
    "name": "63 MM x 4 KG/CM2",
    "category": "X PVC MAIN LINE & SUBMAIN LINE (Rigid PVC Pipe as per IS-4985-1999 with ISI Markings)",
    "unit": "Mtr",
    "costPrice": 96.0,
    "sellingPrice": 96.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-100",
    "name": "50 MM x 6 KG/CM2",
    "category": "X PVC MAIN LINE & SUBMAIN LINE (Rigid PVC Pipe as per IS-4985-1999 with ISI Markings)",
    "unit": "Mtr",
    "costPrice": 90.0,
    "sellingPrice": 90.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  },
  {
    "sku": "ODISHA-DRIP-101",
    "name": "40 MM x 6 KG/CM2",
    "category": "X PVC MAIN LINE & SUBMAIN LINE (Rigid PVC Pipe as per IS-4985-1999 with ISI Markings)",
    "unit": "Mtr",
    "costPrice": 70.0,
    "sellingPrice": 70.0,
    "quantity": 0,
    "stock": 0,
    "lowStockLimit": 0,
    "source": "Odisha Govt Drip Price List 2026-27"
  }
];
